{% set name = "cmseq" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fbeghini/cmseq/archive/{{version}}.tar.gz
  sha256: 37f202a6bf6668ebda5ccfdab878af277a46965e39fa1c4602dc12c0ca67b079

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - samtools >=1.0
    - numpy
    - scipy
    - pysam
    - pandas
    - biopython
    - bcbio-gff

test:
  commands:
    - breadth_depth.py --help
    - consensus.py --help
    - polymut.py --help
    - poly.py --help
about:
  home: https://github.com/SegataLab/cmseq
  summary: Set of utilities on sequences and BAM files